MODE_COLUMNS = {
    1: {
        0: "--",
        1: "del_fix",
        2: "nu_fix",
        3: "qaz_fix",
        4: "naz_fix",
        5: "zone",
        6: "--",
    },
    2: {
        0: "--",
        1: "alpha = beta",
        2: "alpha fix",
        3: "beta fix",
        4: "psi_fix",
        5: "--",
        6: "--",
    },
    3: {
        0: "omega fix",
        1: "eta_fix",
        2: "mu_fix",
        3: "chi_fix",
        4: "phi_fix",
        5: "eta = delta/2",
        6: "mu = nu/2",
    },
    4: {
        0: "--",
        1: "eta_fix",
        2: "mu_fix",
        3: "chi_fix",
        4: "phi_fix",
        5: "--",
        6: "--",
    },
    5: {
        0: "--",
        1: "eta_fix",
        2: "mu_fix",
        3: "chi_fix",
        4: "phi_fix",
        5: "--",
        6: "--",
    },
}