#!/usr/bin/env python3

import yaml
import os



def read(filepath='../gui/motor_fields_default.yml'):
    with open(filepath) as file:
        data = yaml.safe_load(file)
        return data

motors = read()

mu = "MU_MOTOR"+'='+motors["MU_MOTOR"]
eta = "ETA_MOTOR"+'='+motors["ETA_MOTOR"]
chi = "CHI_MOTOR"+'='+motors["CHI_MOTOR"]
phi = "PHI_MOTOR"+'='+motors["PHI_MOTOR"]
nu = "NU_MOTOR"+'='+motors["NU_MOTOR"]
delta = "DEL_MOTOR"+'='+motors["DEL_MOTOR"]

print(mu,eta,chi,phi,nu,delta)

# Call './motors_gui --help' for options
os.system("pydm --hide-nav-bar -m '{} {} {} {} {} {}' ../gui/daf_gui.py".format(mu,eta,chi,phi,nu,delta))

# It is also possible to call it in pydm traditional way. For example:

# pydm -m "ENABLE_SETTINGS=True, M1=SOL:m1, M2=SOL:m2, M3=SOL:m3, ..., MN=SOL:mN" \
# motors_gui.py --debug
