FROM python:3

RUN apt-get update; apt-get upgrade

RUN pip install numpy
RUN pip install scipy
RUN pip install six
RUN pip install h5py
RUN pip install pandas
RUN pip install tqdm
RUN pip install xrayutilities
COPY . /opt/pyscript
RUN mkdir /opt/pyscript/scans
RUN cat /opt/pyscript/q2ang_fit.py > /usr/local/lib/python3.8/site-packages/xrayutilities/q2ang_fit.py
 
ENTRYPOINT ["./opt/pyscript/testescript.py"]

