#!/usr/bin/env python3

import numpy as np
import pandas as pd

from daf.utils.decorators import cli_decorator
from daf.command_line.cli_base_utils import CLIBase
from daf.command_line.scan.daf_scan_utils import ScanBase
from daf.command_line.scan.scan_request import ScanRequest


class FromFileScan(ScanBase):

    DESC = """Perform a scan from a csv file generated by daf.hscan"""
    EPI = """
    Eg:
        daf.ffscan my_scan -t 0.01

        """

    def __init__(self):
        super().__init__(scan_type="list_scan")
        self.exp = self.build_exp()

    def parse_command_line(self):
        CLIBase.parse_command_line(self)
        self.parser.add_argument(
            "file_name",
            type=str,
            help="Perform a scan from the file generated by daf.hscan",
        )
        self.common_cli_scan_arguments(step=False)
        args = self.parser.parse_args()
        return args

    def generate_data_for_scan(self, full_file_path: str) -> np.array:
        """Generate the scan path for scans"""
        scan_points = pd.read_csv(full_file_path)
        data_for_scan = {
            motor: [[float(i) for i in scan_points[motor.capitalize()]]]
            for motor in self._MOTOR_NAMES
        }
        ordered_motors = list(data_for_scan.keys())

        return data_for_scan, ordered_motors

    def configure_scan_input(self):
        """Basically, a wrapper for configure_scan_inputs. It may differ from scan to scan"""
        data_for_scan, ordered_motors = self.generate_data_for_scan(
            self.parsed_args_dict["file_name"]
        )
        inputed_motors = [i for i in data_for_scan.keys()]
        return ScanRequest(
            scan_data=data_for_scan,
            motors=inputed_motors,
            motors_data=self.experiment_file_dict["motors"],
            counters=self.get_counters(),
            main_counter=self.experiment_file_dict.get("main_scan_counter"),
            scan_type=self.scan_type,
            steps=None,
            acquisition_time=self.parsed_args_dict["time"],
            output=self.parsed_args_dict["output"],
            kafka_topic=self.experiment_file_dict.get("kafka_topic"),
            scan_db=self.experiment_file_dict.get("scan_db"),
            kafka_server=self.experiment_file_dict.get("kafka_server"),
        ).to_daf_scan_inputs()

    def run_cmd(self):
        """
        Method to be defined be each subclass, this is the method
        that should be run when calling the cli interface
        """
        self.run_scan()


@cli_decorator
def main() -> None:
    obj = FromFileScan()
    obj.run_cmd()


if __name__ == "__main__":
    main()
