PV_PREFIX = "daf:"

motors = {
    "mu": {
        "pv": PV_PREFIX + "m1",
        "mnemonic": "mu",
        "value": 0,
        "bounds": [-20.0, 160.0],
        "cli_abbrev": "m",
        "up": 1,
    },
    "eta": {
        "pv": PV_PREFIX + "m2",
        "mnemonic": "eta",
        "value": 0,
        "bounds": [-20.0, 160.0],
        "cli_abbrev": "e",
        "up": 1,
    },
    "chi": {
        "pv": PV_PREFIX + "m3",
        "mnemonic": "chi",
        "value": 0,
        "bounds": [-5.0, 95.0],
        "cli_abbrev": "c",
        "up": 1,
    },
    "phi": {
        "pv": PV_PREFIX + "m4",
        "mnemonic": "phi",
        "value": 0,
        "bounds": [-400.0, 400.0],
        "cli_abbrev": "p",
        "up": 1,
    },
    "nu": {
        "pv": PV_PREFIX + "m5",
        "mnemonic": "nu",
        "value": 0,
        "bounds": [-20.0, 160.0],
        "cli_abbrev": "n",
        "up": 1,
    },
    "del": {
        "pv": PV_PREFIX + "m6",
        "mnemonic": "del",
        "value": 0,
        "bounds": [-20.0, 160.0],
        "cli_abbrev": "d",
        "up": 1,
    },
    "sample_z": {  # sz (Sample z - Sample Stage 1 and 2)
        "pv": PV_PREFIX + "m7",
        "mnemonic": "sz",
        "value": 0,
        "bounds": [-20.0, 160.0],
        "cli_abbrev": "sz",
        "up": 1,
    },
    "sample_x": {  # sx (Sample x - Sample Stage 2)
        "pv": PV_PREFIX + "m8",
        "mnemonic": "sx",
        "value": 0,
        "bounds": [-20.0, 160.0],
        "cli_abbrev": "sx",
        "up": 1,
    },
    "sample_rx": {  # srx (Sample Rx - Sample Stage 2)
        "pv": PV_PREFIX + "m9",
        "mnemonic": "srx",
        "value": 0,
        "bounds": [-5.0, 95.0],
        "cli_abbrev": "srx",
        "up": 1,
    },
    "sample_y": {  # sy (Sample y - Sample Stage 2)
        "pv": PV_PREFIX + "m10",
        "mnemonic": "sy",
        "value": 0,
        "bounds": [-400.0, 400.0],
        "cli_abbrev": "sy",
        "up": 1,
    },
    "sample_ry": {  # sry (Sample Ry - Sample Stage 2)
        "pv": PV_PREFIX + "m11",
        "mnemonic": "sry",
        "value": 0,
        "bounds": [-20.0, 160.0],
        "cli_abbrev": "sry",
        "up": 1,
    },
    "sample_x_s1": {  # sx1 (Sample x - Sample Stage 1)
        "pv": PV_PREFIX + "m12",
        "mnemonic": "sx1",
        "value": 0,
        "bounds": [-20.0, 160.0],
        "cli_abbrev": "sx1",
        "up": 1,
    },
    "sample_y_s1": {  # sy1 (Sample y - Sample Stage 1)
        "pv": PV_PREFIX + "m13",
        "mnemonic": "sy1",
        "value": 0,
        "bounds": [-20.0, 160.0],
        "cli_abbrev": "sy1",
        "up": 1,
    },
    "diffractomer_ux": {  # diffux (Diffractometer Ux)
        "pv": PV_PREFIX + "m14",
        "mnemonic": "diffux",
        "value": 0,
        "bounds": [-20.0, 160.0],
        "cli_abbrev": "diffux",
        "up": 1,
    },
    "diffractomer_uy": {  # diffuy (Diffractometer Uy)
        "pv": PV_PREFIX + "m15",
        "mnemonic": "diffuy",
        "value": 0,
        "bounds": [-5.0, 95.0],
        "cli_abbrev": "diffuy",
        "up": 1,
    },
    "diffractomer_rx": {  # diffrx (Diffractometer Rx)
        "pv": PV_PREFIX + "m16",
        "mnemonic": "diffrx",
        "value": 0,
        "bounds": [-400.0, 400.0],
        "cli_abbrev": "diffrx",
        "up": 1,
    },
    "theta_analyzer_crystal": {  # thca (Theta Crystal An.)
        "pv": PV_PREFIX + "m17",
        "mnemonic": "thca",
        "value": 0,
        "bounds": [-20.0, 160.0],
        "cli_abbrev": "thca",
        "up": 1,
    },
    "2theta_analyzer_crystal": {  # tthca (2Theta Crystal An.)
        "pv": PV_PREFIX + "m18",
        "mnemonic": "tthca",
        "value": 0,
        "bounds": [-20.0, 160.0],
        "cli_abbrev": "tthca",
        "up": 1,
    },
}
