motors = {
    "mu": {
        "pv": "SOL:S:m1",
        "mnemonic": "Mu",
        "value": 0,
        "bounds": [-20.0, 160.0],
        "scan_utils_mnemonic": "sol_m1",
    },
    "eta": {
        "pv": "SOL:S:m2",
        "mnemonic": "Eta",
        "value": 0,
        "bounds": [-20.0, 160.0],
        "scan_utils_mnemonic": "sol_m2",
    },
    "chi": {
        "pv": "SOL:S:m3",
        "mnemonic": "Chi",
        "value": 0,
        "bounds": [-5.0, 95.0],
        "scan_utils_mnemonic": "sol_m3",
    },
    "phi": {
        "pv": "SOL:S:m4",
        "mnemonic": "Phi",
        "value": 0,
        "bounds": [-400.0, 400.0],
        "scan_utils_mnemonic": "sol_m4",
    },
    "nu": {
        "pv": "SOL:S:m5",
        "mnemonic": "Nu",
        "value": 0,
        "bounds": [-20.0, 160.0],
        "scan_utils_mnemonic": "sol_m5",
    },
    "del": {
        "pv": "SOL:S:m6",
        "mnemonic": "Del",
        "value": 0,
        "bounds": [-20.0, 160.0],
        "scan_utils_mnemonic": "sol_m6",
    },
    "sample_z": {  # sz (Sample z - Sample Stage 1 and 2)
        "pv": "SOL:S:m7",
        "mnemonic": "sz",
        "value": 0,
        "bounds": [-20.0, 160.0],
        "scan_utils_mnemonic": "sol_m7",
    },
    "sample_x": {  # sx (Sample x - Sample Stage 2)
        "pv": "SOL:S:m8",
        "mnemonic": "sx",
        "value": 0,
        "bounds": [-20.0, 160.0],
        "scan_utils_mnemonic": "sol_m8",
    },
    "sample_rx": {  #  srx (Sample Rx - Sample Stage 2)
        "pv": "SOL:S:m9",
        "mnemonic": "srx",
        "value": 0,
        "bounds": [-5.0, 95.0],
        "scan_utils_mnemonic": "sol_m9",
    },
    "sample_y": {  #  sy (Sample y - Sample Stage 2)
        "pv": "SOL:S:m10",
        "mnemonic": "sy",
        "value": 0,
        "bounds": [-400.0, 400.0],
        "scan_utils_mnemonic": "sol_m10",
    },
    "sample_ry": {  # sry (Sample Ry - Sample Stage 2)
        "pv": "SOL:S:m11",
        "mnemonic": "sry",
        "value": 0,
        "bounds": [-20.0, 160.0],
        "scan_utils_mnemonic": "sol_m11",
    },
    "sample_x_s1": {  # sx1 (Sample x - Sample Stage 1)
        "pv": "SOL:S:m12",
        "mnemonic": "sx1",
        "value": 0,
        "bounds": [-20.0, 160.0],
        "scan_utils_mnemonic": "sol_m12",
    },
    "sample_y_s1": {  # sy1 (Sample y - Sample Stage 1)
        "pv": "SOL:S:m13",
        "mnemonic": "sy1",
        "value": 0,
        "bounds": [-20.0, 160.0],
        "scan_utils_mnemonic": "sol_m13",
    },
    "diffractomer_ux": {  #  diffux (Diffractometer Ux)
        "pv": "SOL:S:m14",
        "mnemonic": "diffux",
        "value": 0,
        "bounds": [-20.0, 160.0],
        "scan_utils_mnemonic": "sol_m14",
    },
    "diffractomer_uy": {  #  diffuy (Diffractometer Uy)
        "pv": "SOL:S:m15",
        "mnemonic": "diffuy",
        "value": 0,
        "bounds": [-5.0, 95.0],
        "scan_utils_mnemonic": "sol_m15",
    },
    "diffractomer_rx": {  #  diffrx (Diffractometer Rx)
        "pv": "SOL:S:m16",
        "mnemonic": "diffrx",
        "value": 0,
        "bounds": [-400.0, 400.0],
        "scan_utils_mnemonic": "sol_m16",
    },
    "theta_analyzer_crystal": {  #  thca (Theta Crystal An.)
        "pv": "SOL:S:m17",
        "mnemonic": "thca",
        "value": 0,
        "bounds": [-20.0, 160.0],
        "scan_utils_mnemonic": "sol_m17",
    },
    "2theta_analyzer_crystal": {  #  tthca (2Theta Crystal An.)
        "pv": "SOL:S:m18",
        "mnemonic": "tthca",
        "value": 0,
        "bounds": [-20.0, 160.0],
        "scan_utils_mnemonic": "sol_m18",
    },
}